[package]
name = "rstris"
version = "0.1.0"
authors = ["Kenny Lorin <kenny.lorin@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.5.0"
nanorand = "0.5.2"
